"""empty message

Revision ID: c85aadcf4706
Revises: f3f03668e60e
Create Date: 2023-07-28 06:26:39.086817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85aadcf4706'
down_revision = 'f3f03668e60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_list_id', sa.Integer(), nullable=True),
    sa.Column('item_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_list_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_list')
    # ### end Alembic commands ###
